<?php

namespace App\Models\ProductionItems;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class ProductionItems extends Model
{
    use HasFactory;


/*  Original Fillable 

    protected $fillable = [
        'item_code',
        'name',
        'description',
        'production_category', 
        'production_location',
        'packaging_id',
        'labor_cost',
        'gas_cost',
        'storage_cost',
        'storage_multiplier',
        'total_storage_cost',
        'storage_location',
        'depreciation',
        'raw_mast_provision',
        'markup_percentage',
        'final_value_vatex',
        'final_value_vatinc',
    ];
*/
protected $table = 'production_items';

protected $fillable = [
    // Existing fillable fields
    'reference_number',
    'description', 
    'production_category',
    'production_location', 
    'labor_cost',
    'opex',
    'gas_cost',
    'utilities',                
    'storage_cost',
    'storage_multiplier',
    'total_storage_cost',
    'storage_location',
    'depreciation',
    'raw_mast_provision',
    'markup_percentage',
    'final_value_vatex',
    'final_value_vatinc',
    'purchase_price',
    'ttp',
    'ttp_price_change',        
    'ttp_price_effective_date', 
    'old_ttp',
    'ttp_percentage',
    'old_ttp_percentage',
    'ttp_percentage_price_change',
    'landed_cost',
    'moq_supplier',
    'moq_store',
    'moq_value',
    'moq_currencies_id',
    'type',
    'item',
    'final_value_existing',
    'suppliers_id',
    'trademarks_id',
    'classifications_id',
    'supplier_item_code',
    'myob_item_description',
    'full_item_description',
    'brands_id',
    'groups_id',
    'categories_id',
    'subcategories_id',
    'types_id',
    'colors_id',
    'actual_color',
    'flavor',
    'packaging_size',
    'packaging_cost',
    'packaging_dimension',
    'uoms_id',
    'packagings_id',
    'vendor_types_id',
    'inventory_types_id',
    'sku_statuses_id',
    'tax_codes_id',
    'currencies_id',
    'chart_accounts_id',
    'fulfillment_type_id',
    'accounts_id',
    'asset_accounts_id',
    'action_type',
    'cogs_accounts_id',
    'quantity_on_hand',
    'accumulated_depreciation',
    'tax_agency',
    'transfer_price_category',
    'price',
    'reorder_pt',
    'mpn',
    'uoms_set_id',
    'tax_status',
    'purchase_description',
    'image_filename',
    'file_link', 
    'segmentation',
    'segmentation_any',
    'segmentation_bbd',
    'segmentation_eyb',
    'segmentation_cbl',
    'segmentation_com',
    'segmentation_fmr',
    'segmentation_fwb',
    'segmentation_fzb',
    'segmentation_hmk',
    'segmentation_htw',
    'segmentation_kkd',
    'segmentation_lps',
    'segmentation_lbs',
    'segmentation_mtd',
    'segmentation_ppd',
    'segmentation_pze',
    'segmentation_psn',
    'segmentation_ppr',
    'segmentation_rcf',
    'segmentation_scb',
    'segmentation_sch',
    'segmentation_sdh',
    'segmentation_smk',
    'segmentation_twu',
    'segmentation_tbf',
    'segmentation_tgd',
    'segmentation_wkd',
    'segmentation_wks',
    'segmentation_wmn',
    'segmentation_1',
    'segmentation_2',
    'segmentation_3',
    'segmentation_4',
    'segmentation_5',
    'segmentation_6',
    'segmentation_7',
    'segmentation_8',
    'segmentation_9',
    'segmentation_10',
    'segmentation_11',
    'segmentation_12',
    'segmentation_13',
    'segmentation_14',
    'segmentation_15',
    'segmentation_16',
    'segmentation_17',
    'segmentation_18',
    'segmentation_19',
    'segmentation_20',
    'segmentation_21',
    'segmentation_22',
    'segmentation_slb',
    'segmentation_dgb',
    'segmentation_scp',
    'segmentation_sck',
    'segmentation_tdc',
    'segmentation_twn',
    'segmentation_rcs',
    'segmentation_bob',
    'segmentation_drp',
    'segmentation_bev',
    'segmentation_ten',
    'segmentation_ahw',
    'segmentation_tmt',
    'segmentation_mks',
    'segmentation_bkh',
    'segmentation_mni',
    'segmentation_mor',
    'segmentation_kkg',
    'segmentation_fab',
    'segmentation_tai',
    'segmentation_sea',
    'segmentation_bnh',
    'segmentation_nom',
    'segmentation_tbb',
    'segmentation_wtf',
    'segmentation_spc',
    'segmentation_spb',
    'segmentation_crp',
    'segmentation_cor',
    'segmentation_cpl',
    'segmentation_cmp', 
    'labor_cost_per_minute',
    'total_minutes_per_pack',
    'labor_cost_val',  
    'approved_by',
    'approval_status',
    'approved_at',
    'created_by',
    'updated_by',
];


    public function itemLines(): HasMany{
        return $this->hasMany(ProductionItemLines::class, 'production_item_id');
    }
}


